#!/usr/bin/env python3
"""
Bulk destroy workspaces from a list file.

Supports full teardown: pipeline unbinding, item deletion, then
workspace deletion.  Each workspace line in the input file is treated
as a complete workspace display name (spaces allowed).  Lines starting
with ``#`` are comments; blank lines are skipped.

File format (one workspace per line)::

    # Test workspaces to destroy
    E2E Test Consumer [DEV]
    E2E Test Consumer [TEST]
    edp-test-v17 [DEV]
"""

import argparse
import logging
import sys
import time
from pathlib import Path

from usf_fabric_cli.services.fabric_wrapper import FabricCLIWrapper
from usf_fabric_cli.utils.config import get_environment_variables

logger = logging.getLogger(__name__)

# Items of these types are auto-generated by Fabric and cannot be
# deleted directly — skip them during item cleanup.
_SKIP_ITEM_TYPES = frozenset(
    {
        "SQLEndpoint",
        "GraphQLApi",
        "DatasetSQLEndpoint",
    }
)


def parse_workspace_list(file_path):
    """Parse workspace names from a text file.

    Each non-blank, non-comment line is one workspace display name.
    Trailing ``.Workspace`` suffixes are stripped for convenience.
    """
    workspaces = []
    with open(file_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            # The full line is the workspace name (spaces are valid)
            name = line

            # Strip .Workspace suffix if someone pasted fab ls output
            if name.endswith(".Workspace"):
                name = name[: -len(".Workspace")]

            workspaces.append(name)
    return workspaces


def _build_pipeline_map(token):
    """Build a workspace_id → [(pipeline_id, pipeline_name, stage_id, stage_name)] map.

    Scans all deployment pipelines once and indexes their stage bindings.
    This turns per-workspace pipeline discovery from O(pipelines) API
    calls into a single upfront O(pipelines) scan followed by O(1)
    lookups per workspace.

    Fabric API rate-limits the deployment pipeline endpoints aggressively,
    so a 3-second delay is inserted between stage lookups.
    """
    from usf_fabric_cli.services.deployment_pipeline import (
        FabricDeploymentPipelineAPI,
    )

    pipeline_api = FabricDeploymentPipelineAPI(token)
    # workspace_id -> list of (pipeline_id, pipeline_name, stage_id, stage_name)
    ws_map = {}

    pipelines_result = pipeline_api.list_pipelines()
    if not pipelines_result.get("success"):
        print("  [WARN] Could not list deployment pipelines")
        return ws_map, pipeline_api

    pipelines = pipelines_result.get("pipelines", [])
    if not pipelines:
        return ws_map, pipeline_api

    print(f"  Scanning {len(pipelines)} deployment pipelines for workspace bindings...")
    scanned = 0
    failed = 0
    for pipeline in pipelines:
        pipeline_id = pipeline.get("id", "")
        pipeline_name = pipeline.get("displayName", pipeline_id)

        # Throttle to avoid 429 rate limits (Fabric is aggressive
        # on deployment pipeline endpoints with 20+ pipelines).
        time.sleep(3)

        stages_result = pipeline_api.get_pipeline_stages(pipeline_id)
        if not stages_result.get("success"):
            failed += 1
            continue

        scanned += 1
        for stage in stages_result.get("stages", []):
            ws_id = stage.get("workspaceId")
            if ws_id:
                stage_name = stage.get("displayName", stage["id"])
                stage_id = stage["id"]
                ws_map.setdefault(ws_id, []).append(
                    (pipeline_id, pipeline_name, stage_id, stage_name)
                )

    print(f"  Scanned {scanned}/{len(pipelines)} pipelines ({failed} failed)")
    bound_count = sum(len(v) for v in ws_map.values())
    print(
        f"  Found {bound_count} workspace-stage bindings"
        f" across {len(ws_map)} workspaces"
    )

    return ws_map, pipeline_api


def _teardown_pipeline_for_workspace(
    fabric, workspace_name, pipeline_map, pipeline_api
):
    """Unassign workspace from any deployment pipeline stages.

    Uses the pre-built pipeline_map for O(1) lookup instead of
    scanning all pipelines per workspace.

    Fabric refuses to delete workspaces connected to ALM deployment
    pipelines — this step unbinds them first.
    """
    workspace_id = fabric.get_workspace_id(workspace_name)
    if not workspace_id:
        print("    Could not resolve workspace ID — skipping pipeline teardown")
        return

    bindings = pipeline_map.get(workspace_id, [])
    if not bindings:
        print("    No pipeline bindings found")
        return

    for pipeline_id, pipeline_name, stage_id, stage_name in bindings:
        unassign = pipeline_api.unassign_workspace_from_stage(pipeline_id, stage_id)
        if unassign.get("success"):
            print(
                f"    Unassigned from pipeline '{pipeline_name}' "
                f"stage '{stage_name}'"
            )
        else:
            print(
                f"    [WARN] Failed to unassign from "
                f"'{pipeline_name}/{stage_name}': "
                f"{unassign.get('error', '')}"
            )


def _delete_workspace_items(fabric, workspace_name):
    """Delete all deletable items in a workspace before destroying it.

    Some Fabric item types (SQLEndpoint, GraphQLApi) are auto-managed
    and cannot be deleted directly — those are skipped.
    """
    items = fabric.list_workspace_items_api(workspace_name)
    if not items:
        return 0

    deleted = 0
    for item in items:
        item_type = item.get("type", "Unknown")
        item_name = item.get("displayName", "?")

        if item_type in _SKIP_ITEM_TYPES:
            continue

        path = f"{workspace_name}.Workspace/{item_name}.{item_type}"
        result = fabric._execute_command(["rm", path, "--force"], timeout=60)
        if result.get("success"):
            print(f"    Deleted {item_type}: {item_name}")
            deleted += 1
        else:
            error = str(result.get("error", ""))
            # Not-found is fine — item may have been cascade-deleted
            if "NotFound" in error or "could not be found" in error.lower():
                continue
            print(f"    [WARN] Could not delete {item_type} '{item_name}': {error}")

    return deleted


def bulk_destroy(
    file_path,
    dry_run=False,
    force=False,
    teardown_pipelines=True,
    delete_items=True,
):
    workspaces = parse_workspace_list(file_path)

    if not workspaces:
        print("No workspaces found in file.")
        return

    print(f"Found {len(workspaces)} workspaces to delete:")
    for ws in workspaces:
        print(f"  - {ws}")

    if teardown_pipelines:
        print("\nPipeline teardown: ENABLED")
    if delete_items:
        print("Item deletion: ENABLED")

    if dry_run:
        print("\n[Dry Run] No actions taken.")
        return

    if not force:
        confirm = input(
            "\nAre you sure you want to delete these workspaces? (yes/no): "
        )
        if confirm.lower() != "yes":
            print("Operation cancelled.")
            return

    # Initialize wrapper
    try:
        env_vars = get_environment_variables()
        token = env_vars.get("FABRIC_TOKEN", "")
        fabric = FabricCLIWrapper(token)
    except (ValueError, OSError, RuntimeError) as e:
        print(f"Error initializing Fabric wrapper: {e}")
        return

    # Build pipeline→workspace map once upfront (O(pipelines) API calls)
    # instead of scanning all pipelines per workspace (O(workspaces × pipelines)).
    pipeline_map = {}
    pipeline_api = None
    if teardown_pipelines:
        print("\nBuilding pipeline binding map...")
        pipeline_map, pipeline_api = _build_pipeline_map(token)

    print("\nStarting deletion...")
    success_count = 0
    fail_count = 0
    skip_count = 0

    for ws in workspaces:
        print(f"\n{'='*60}")
        print(f"Workspace: {ws}")
        print(f"{'='*60}")

        try:
            # Step 1: Teardown deployment pipeline bindings (O(1) lookup)
            if teardown_pipelines:
                print("  [1/3] Tearing down pipeline bindings...")
                _teardown_pipeline_for_workspace(fabric, ws, pipeline_map, pipeline_api)

            # Step 2: Delete all items in workspace
            if delete_items:
                print("  [2/3] Deleting workspace items...")
                items_deleted = _delete_workspace_items(fabric, ws)
                print(f"    {items_deleted} items deleted")

            # Step 3: Delete the workspace itself
            print("  [3/3] Deleting workspace...")
            result = fabric.delete_workspace(ws)

            if result.get("success"):
                print(f"  [OK] Workspace '{ws}' destroyed")
                success_count += 1
            else:
                error = str(result.get("error", ""))
                if "NotFound" in error or "could not be found" in error.lower():
                    print(f"  [SKIP] Workspace '{ws}' not found — already gone")
                    skip_count += 1
                else:
                    print(f"  [ERROR] Failed: {error}")
                    fail_count += 1

        except (ValueError, KeyError, OSError, RuntimeError) as e:
            print(f"  [ERROR] Exception: {e}")
            fail_count += 1

    print(f"\n{'='*60}")
    print(
        f"Summary: {success_count} deleted,"
        f" {skip_count} skipped, {fail_count} failed"
    )
    print(f"{'='*60}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Bulk destroy workspaces (with pipeline teardown + item deletion)"
    )
    parser.add_argument(
        "file",
        help="Path to file containing workspace names (one per line)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be deleted without doing it",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Skip confirmation prompt",
    )
    parser.add_argument(
        "--skip-pipeline-teardown",
        action="store_true",
        help="Skip deployment pipeline unassignment before deletion",
    )
    parser.add_argument(
        "--skip-item-deletion",
        action="store_true",
        help="Skip deleting workspace items before workspace deletion",
    )

    args = parser.parse_args()

    if not Path(args.file).exists():
        print(f"Error: File {args.file} not found")
        return 1

    bulk_destroy(
        args.file,
        dry_run=args.dry_run,
        force=args.force,
        teardown_pipelines=not args.skip_pipeline_teardown,
        delete_items=not args.skip_item_deletion,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
