# Extensive Fabric Workspace Configuration Example
# This file demonstrates the full capabilities of the configuration schema.

workspace:
  name: "Enterprise_Analytics_Hub"
  display_name: "Enterprise Analytics Hub"
  description: "Centralized analytics platform for cross-functional data products."
  capacity_id: "${FABRIC_CAPACITY_ID}" # Use environment variable for portability
  domain: "Finance" # Assign to a specific Fabric Domain (if configured)
  
  # Git Integration (Optional)
  # Connects the workspace to a specific Git repository and branch for version control.
  git_repo: "https://github.com/your-org/enterprise-analytics"
  git_branch: "main"
  git_directory: "/fabric-artifacts"

# Folder Structure (Medallion Architecture + Functional Areas)
# These folders are created in the workspace to organize items.
folders:
  - "Bronze"
  - "Silver"
  - "Gold"
  - "Notebooks"
  - "Pipelines"
  - "SemanticModels"
  - "Reports"

# Lakehouses (Data Engineering)
lakehouses:
  - name: "raw_landing_zone"
    folder: "Bronze"
    description: "Landing zone for raw data ingestion from external sources."
  
  - name: "enriched_data_zone"
    folder: "Silver"
    description: "Cleaned, deduplicated, and enriched data tables."

# Warehouses (Data Warehousing)
warehouses:
  - name: "enterprise_dw"
    folder: "Gold"
    description: "Star-schema data warehouse for high-performance reporting."

# Notebooks (Code-First Engineering)
notebooks:
  - name: "ingest_sales_data"
    folder: "Notebooks"
    description: "PySpark notebook to ingest sales data from API."
    file_path: "src/notebooks/ingest_sales.ipynb" # Optional: Upload content from local file

  - name: "transform_customer_dim"
    folder: "Notebooks"
    description: "Transformation logic for Customer dimension."

# Pipelines (Orchestration)
pipelines:
  - name: "daily_etl_orchestrator"
    folder: "Pipelines"
    description: "Master pipeline triggering ingestion and transformation flows."

# Semantic Models (BI & Reporting)
semantic_models:
  - name: "sales_performance_model"
    folder: "SemanticModels"
    description: "Certified dataset for Sales Performance reporting."

# Principals (Security & Access Control)
# IMPORTANT: Use Object IDs (GUIDs), not email addresses.
principals:
  - id: "${ADMIN_GROUP_OID}" # e.g., "d0555555-5555-5555-5555-555555555555"
    role: "Admin"
  
  - id: "${DEVELOPER_GROUP_OID}" # e.g., "e0555555-5555-5555-5555-555555555555"
    role: "Member"
  
  - id: "${ANALYST_GROUP_OID}" # e.g., "f0555555-5555-5555-5555-555555555555"
    role: "Viewer"
  
  - id: "${SERVICE_PRINCIPAL_OID}" # e.g., "88e55555-5555-5555-5555-555555555555"
    role: "Contributor"

# Generic Resources (Future-Proofing)
# Use this for item types not yet explicitly supported by the schema but supported by the API.
resources:
  - type: "Eventstream"
    name: "iot_telemetry_stream"
    description: "Real-time stream of IoT device telemetry."
    folder: "Bronze"

  - type: "KQLDatabase"
    name: "log_analytics_db"
    description: "Kusto database for application log analysis."
    folder: "Silver"
