# Medallion Architecture Blueprint
# Standardizes data processing layers: Bronze (Raw) -> Silver (Enriched) -> Gold (Curated)
# Designed for: Scalable data engineering, clear data lineage, auditability

workspace:
  name: "Medallion_Project"
  display_name: "Medallion Data Product"
  description: "Data product implementing Medallion Architecture (Bronze/Silver/Gold)"
  capacity_id: "${FABRIC_CAPACITY_ID}"
  domain: "${FABRIC_DOMAIN_NAME}" # Optional: assign to a governance domain
  
  # Git Integration
  git_repo: "${GIT_REPO_URL}"
  git_branch: "main"
  git_directory: "/"

# Folder Structure (Medallion Layers)
folders:
  - "Bronze"    # Raw / Ingestion layer
  - "Silver"    # Cleaned / Validated layer
  - "Gold"      # Aggregated / Business-ready layer
  - "Utilities" # Helper scripts and tools
  - "Pipelines" # Orchestration logic

# Lakehouses (One per layer is a common pattern for isolation)
lakehouses:
  - name: "lh_bronze"
    folder: "Bronze"
    description: "Raw data ingestion landing zone. immutable, append-only."
  
  - name: "lh_silver"
    folder: "Silver"
    description: "Cleaned, deduplicated, and validated data."
  
  - name: "lh_gold"
    folder: "Gold"
    description: "Star schema / dimensional models for reporting."

# Warehouses (Serving Layer - Optional, often mapped to Gold)
warehouses:
  - name: "wh_serving"
    folder: "Gold"
    description: "SQL-accessible serving layer for BI tools."

# Notebooks (Transformation Logic)
notebooks:
  - name: "ingest_to_bronze"
    folder: "Bronze"
    description: "Generic ingestion framwork for raw data."
  
  - name: "bronze_to_silver_quality"
    folder: "Silver"
    description: "Quality checks and standardization (Bronze -> Silver)."
  
  - name: "silver_to_gold_agg"
    folder: "Gold"
    description: "Business logic aggregation and dimensional modeling (Silver -> Gold)."

# Pipelines (Orchestration)
pipelines:
  - name: "marketing_data_refresh"
    folder: "Pipelines"
    description: "Daily refresh pipeline: Ingest -> Silver -> Gold."

# Principals (Security & Access Control)
principals:
  # Project Owner / Lead Engineer
  - id: "${DEV_ADMIN_OBJECT_ID}"
    role: "Admin"
    description: "Project Owner / Admin"
  
  # Data Engineering Team
  - id: "${DEV_CONTRIBUTOR_OBJECT_ID}"
    role: "Contributor"
    description: "Data Engineering Team"
  
  # Business Analysts (Read-only)
  - id: "${PROD_VIEWERS_GROUP_ID}"
    role: "Viewer"
    description: "Business Analysts (Consumption only)"

  # Automation Service Principal (CI/CD)
  - id: "${AZURE_CLIENT_ID}"
    role: "Contributor"
    description: "Service Principal for CI/CD automation"

  # Mandatory Enterprise Principals
  - id: "${ADDITIONAL_ADMIN_PRINCIPAL_ID}"
    role: "Admin"
    description: "Enterprise Admin"
  
  - id: "${ADDITIONAL_CONTRIBUTOR_PRINCIPAL_ID}"
    role: "Contributor"
    description: "Enterprise Contributor"

# Environment Overrides
# NOTE: Inline environments: blocks are NOT read by ConfigManager.
# Use config/environments/{dev,test,prod}.yaml for per-environment overrides.
# Example overrides (place in config/environments/dev.yaml):
#   workspace:
#     name: "Medallion_Dev"
#     capacity_id: "${DEV_CAPACITY_ID}"
