# Project Configuration for usf_fabric_cli_cicd
# Based on basic_etl.yaml template

workspace:
  name: "usf-fabric-cli-cicd-workspace"
  display_name: "USF Fabric CLI CICD Workspace"
  description: "Workspace for USF Fabric CLI CICD Project"
  capacity_id: "${FABRIC_CAPACITY_ID}"
  
  # Git integration
  git_repo: "${GIT_REPO_URL}"
  git_branch: "main"
  git_directory: "/"

# Folder structure (medallion architecture)
folders:
  - "Bronze"
  - "Silver"
  - "Gold"
  - "Notebooks"
  - "Pipelines"

# Lakehouses
lakehouses:
  - name: "raw_lakehouse"
    folder: "Bronze"
    description: "Raw data landing zone"
  
  - name: "processed_lakehouse"
    folder: "Silver"
    description: "Processed data zone"

# Warehouses
warehouses:
  - name: "analytics_warehouse"
    folder: "Gold"
    description: "Analytics warehouse"

# Notebooks
notebooks:
  - name: "demo_notebook"
    folder: "Notebooks"
    description: "Demo notebook"

# Pipelines
pipelines:
  - name: "demo_pipeline"
    folder: "Pipelines"
    description: "Demo pipeline"

# Principals
principals:
  - id: "${DEV_ADMIN_OBJECT_ID}"
    role: "Admin"
  
  - id: "${AZURE_CLIENT_ID}"
    role: "Contributor"

  - id: "${ADDITIONAL_ADMIN_PRINCIPAL_ID}"
    role: "Admin"
    description: "Mandatory Additional Admin"
  
  - id: "${ADDITIONAL_CONTRIBUTOR_PRINCIPAL_ID}"
    role: "Contributor"
    description: "Mandatory Additional Contributor"
